from k8s_client import get_k8s_client, local_persistent_volume
from kubernetes import client, config, watch

def get_client():
    host = config.kube_config.Configuration.get_default_copy().host
    print(host)
    return get_k8s_client(host, 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkkyQVJNRkMwODhrcnUtRUtuV2VwLWtPcm1faVNsWlNpWV9GNmZoMnVKeDgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJqaHViIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InZvbHVtZS1tYW5hZ2VyLXRva2VuLXo3ZGhyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InZvbHVtZS1tYW5hZ2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTUxNzBmMjMtZTRkYi00NTJlLTgxZjEtMDE5NTc2Mzg5ZjViIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmpodWI6dm9sdW1lLW1hbmFnZXIifQ.xyuHsjbyCqUblDObAcN0CQdBhIz3lMIIfOtj60gQ6Z6RC-u28fJN1SARaVwvvZ2oxVhHUWvdIkCmRLzBoJN9Sfu-ISLDa3h_lwmjrgszAKKlUm2Coy2TzrsP8yqoixNj6197ZIcjZDBZMH-KgeiWqRWDTa1JJdakaNIYOY9RQLXU7ytVBFMUTdzydar_3QPtcrectAG3STmFErQjooQs9OR0qQ15Uthy1JuPWjVYXPxFP8ICaG4YswrguZh73s3FPDrYMQYkdXybq_rSxYRppa1yUdth8aAwj49-tftZ0K98JKcB9sGBr6htUgiiuTdswrbdJg1ogFNcwtgQa3b8cQ')

def get_local(v1, volumeName, size, path, hostname, namespace):
    local_persistent_volume(v1, volumeName, size, path, hostname, namespace);