
function createOrg() {
  ORG=$1
  PORT=$2
  
  infoln "Enrolling the CA admin"
  mkdir -p ${PWD}/crypto-config/peerOrganizations/$ORG.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/crypto-config/peerOrganizations/$ORG.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:$PORT --caname ca-$ORG --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-$PORT-ca-$ORG.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-$PORT-ca-$ORG.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-$PORT-ca-$ORG.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-$PORT-ca-$ORG.pem
    OrganizationalUnitIdentifier: orderer" > "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org's CA cert to org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/msp/tlscacerts/ca.crt"

  # Copy org's CA cert to org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/tlsca"
  cp "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/tlsca/tlsca.$ORG.example.com-cert.pem"

  # Copy org's CA cert to org's /ca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/ca"
  cp "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/ca/ca.$ORG.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-$ORG --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-$ORG --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-$ORG --id.name "admin$ORG" --id.secret "adminpw$ORG" --id.type admin --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:$PORT --caname ca-$ORG -M "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/msp" --csr.hosts peer0.$ORG.example.com --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:$PORT --caname ca-$ORG -M "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls" --enrollment.profile tls --csr.hosts peer0.$ORG.example.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls/tlscacerts/"* "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls/ca.crt"
  cp "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls/signcerts/"* "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls/server.crt"
  cp "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls/keystore/"* "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/peers/peer0.$ORG.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:$PORT --caname ca-$ORG -M "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/users/User1@$ORG.example.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/users/User1@$ORG.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u "https://admin$ORG:adminpw$ORG@localhost:$PORT" --caname ca-$ORG -M "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/users/Admin@$ORG.example.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/$ORG/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/$ORG.example.com/users/Admin@$ORG.example.com/msp/config.yaml"

}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p ${PWD}/crypto-config/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/crypto-config/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-orderer --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/crypto-config/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/crypto-config/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:10054 --caname ca-orderer -M "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/crypto-config/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:10054 --caname ca-orderer -M "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:10054 --caname ca-orderer -M "${PWD}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/crypto-config/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}